In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
              [4,5,6]]) *5
print(a*5)

[[ 25  50  75]
 [100 125 150]]


In [4]:
arr = np.arange(1,20,2).reshape(2,5)
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [5]:
arr = arr.reshape(5,2)
arr

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [6]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.random.random((3,4))

array([[0.05232869, 0.64607302, 0.92882477, 0.36172334],
       [0.9966298 , 0.44290552, 0.09969608, 0.76505222],
       [0.15939219, 0.56494309, 0.89248131, 0.8267561 ]])

In [8]:
np.linspace(10,80,3)

array([10., 45., 80.])

In [13]:
data1 = np.random.randint(0,10000,size=(25000,15))
data1

array([[1915, 2566, 3796, ..., 1348, 2773, 4658],
       [2474, 3082, 4295, ..., 8587, 9294, 9031],
       [5857, 7396, 9104, ..., 6473, 9965, 2363],
       ...,
       [8086, 2030, 9143, ..., 3243, 2330,  766],
       [7594,  861,  958, ..., 5084, 5639, 9341],
       [1939, 8981, 9311, ..., 8448, 6653, 5631]])

In [15]:
data = np.random.random((25000,15)) * 10000
data = data.astype('int32')
# data = data.reshape(25000,15)
data * data1

array([[ 9400735, 15560224, 35143368, ...,  5797748, 25126153,   763912],
       [20098776, 15668888,  2439560, ..., 80116710, 11338680, 57888710],
       [19755661, 73116856, 81280512, ..., 10097880, 66207460,  7176431],
       ...,
       [  355784, 15764980,  9938441, ..., 30477714, 22121020,  6302648],
       [16570108,  5797974,  4506432, ..., 27392592, 14193363, 76867089],
       [19281416, 13579272, 15148997, ..., 73556736, 21442619,  6903606]])