In [1]:
import numpy as np

Create a numpy array from range 2-100 of size 20 and reshape it to 5x4

In [2]:
np.random.seed(42)
arr = np.random.randint(2,100,20)
arr = arr.reshape((5,4))
arr

array([[53, 94, 16, 73],
       [62, 22, 84, 88],
       [76, 76, 89, 25],
       [ 4, 23, 54,  3],
       [89, 31, 39,  3]])

fetch all data till 3rd row and all data till 3rd column

In [3]:
arr[:3,:3]

array([[53, 94, 16],
       [62, 22, 84],
       [76, 76, 89]])

fetch all data from 3rd row and all data from 1st column

In [4]:
arr[3:,:1]

array([[ 4],
       [89]])

all data starting from 2nd row till 3rd row and all data of first and last column

In [5]:
arr[2:4,[0,-1]]

array([[76, 25],
       [ 4,  3]])

In [8]:
rng = np.random.default_rng(seed=100)

x1 = rng.integers(2,100,6)
x2 = rng.integers(2,100,6)
x1,x2

(array([77, 83, 14, 60,  9, 30], dtype=int64),
 array([45,  6, 59, 97, 94, 60], dtype=int64))

In [7]:
x1.T

array([[77, 60],
       [83,  9],
       [14, 30]], dtype=int64)